# 📊 PROMETHEUS CONFIGURATION - SISTEMA PROCURA
# Configuración completa para monitoreo de métricas

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'procura-system'

# ========================================
# RULE FILES
# ========================================
rule_files:
  - "rules/*.yml"

# ========================================
# SCRAPE CONFIGURATIONS
# ========================================
scrape_configs:
  # ========================================
  # PROMETHEUS SELF-MONITORING
  # ========================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # ========================================
  # SISTEMA PROCURA BACKEND
  # ========================================
  - job_name: 'procura-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: /api/metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        regex: '([^:]+)(?::\d+)?'
        replacement: 'procura-backend'

  # ========================================
  # POSTGRESQL DATABASE
  # ========================================
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        regex: '([^:]+)(?::\d+)?'
        replacement: 'postgres'

  # ========================================
  # REDIS CACHE
  # ========================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        regex: '([^:]+)(?::\d+)?'
        replacement: 'redis'

  # ========================================
  # NGINX REVERSE PROXY
  # ========================================
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        regex: '([^:]+)(?::\d+)?'
        replacement: 'nginx'

  # ========================================
  # NODE EXPORTER (SYSTEM METRICS)
  # ========================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        regex: '([^:]+)(?::\d+)?'
        replacement: 'node-exporter'

# ========================================
# ALERTING
# ========================================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# ========================================
# REMOTE WRITE (OPCIONAL)
# ========================================
remote_write:
  - url: "http://remote-write-endpoint:9090/api/v1/write"
    remote_timeout: 30s
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'up|job:up'
        action: drop



